name: Huq BigQuery Package

on:
  push:
    branches:
      - master

jobs:

  bq-package:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      GCLOUD_VERSION: 360.0.0
      BQ_REGION: eu
      BQ_PROJECT: huq-library
      BQ_BUCKET: huq-library
    steps:
    - uses: actions/checkout@v2
      with:
        # We need to limit the fetch depth or this action could fail
        fetch-depth: 5

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
          version: ${{ env.GCLOUD_VERSION }}
          project_id: ${{ env.BQ_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY_GITHUB_CI }}
          export_default_credentials: true

    - name: Create installation package
      run: ./common/bigquery/create_installation_package.sh
